calculator/urls.py
from django.urls import path
from . import views

app_name = 'calcluator'

urlpatterns = [

    path('', views.main_page, name='main_page'),
    path('set_demensions/', views.set_demensions, name='set_demensions'),
    path('result', views.result, name='result'),

]

det_calculator/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calculator.urls', namespace='calculator'))
]

calculator/models.py
from django.db import models

# Create your models here.

calculator/forms.py
from django import forms

# creating a form
class InputForm(forms.Form):
    """A form to get n (matrix demensions number) from user"""

    n = forms.IntegerField(
        max_value=9,
        min_value=1,
        required=True,
        initial=1,
        label = '',
    )

class MatrixInputForm(forms.Form):
    """A form to take members of a matrix"""

    matrix_members = forms.IntegerField(
        required = True,
        initial=0,
        label='',
    )

calculator/views.py
from math import sqrt
import copy
from django.shortcuts import redirect, render
from calculator.forms import InputForm, MatrixInputForm
from django.forms import formset_factory


def two_in_two_matrix(matrix, length):
    """Section one : finding determinant of a 2*2 matrix"""
    determinant = (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])

    return determinant


def minor(matrix, line, column):
    """A function to calculate the minor of a matrix"""

    matrix_copy = copy.deepcopy(matrix)
    
    # Deleting the (line)th line
    del matrix_copy[line]
    # Deleting the (column)th column
    for l in matrix_copy:
        del l[column]

    return matrix_copy


def big_matrix(matrix, length):
    """Section two : finding determinant of a matrix bigger than 2*2"""
    first_line = matrix[0]
    i = 0
    determinant = 0

    # Getting cofactors of each element in the first_line
    for element in first_line :
        
        # Getting minor of the matrix
        matrix_minor =  minor(matrix, 0, i)

        # If the minor of matrix was 2*2 then get the cofactor
        if len(matrix_minor) == 2 :
            if (i + 0) % 2 == 0 :
                cofactor = element * (two_in_two_matrix(matrix_minor, len(matrix_minor)))
            else :
                cofactor = (-1) * element * (two_in_two_matrix(matrix_minor, len(matrix_minor) ))
        # if the minor of the matrix was bigger than 2*2 get minor's det
        else :
            if (i + 0) % 2 == 0 :
                cofactor = element * big_matrix(matrix_minor, len(matrix_minor))
            else :
                cofactor = (-1) * element * big_matrix(matrix_minor, len(matrix_minor))
            
        i = i + 1
        # Summing up the result of cofactors
        determinant = determinant + cofactor

    return determinant


def main_page(request) :
    """Renders main page and gets the n (matrix demension number)"""
    
    if request.method != 'POST' :
        form = InputForm()
    
    else :

        form = InputForm(data=request.POST)
        if form.is_valid() :
            return redirect('calculator:set_demensions')

    context = {'form' : form}
    return render(request, 'calculator/main_page.html', context)


def set_demensions(request) :
    """A page to set numbers of matrix"""

    if 'n' in request.POST :

        demensions_number = int(request.POST['n'])
        matrix_formset = formset_factory(MatrixInputForm, extra = demensions_number * demensions_number)

        formset = matrix_formset()
        
        # See in which forms we go to the next row
        change_place = demensions_number
        change_list = []
        diff = change_place
        
        # See in wich indexes of forms should we go to the next row row
        while (change_place <= demensions_number * demensions_number) :
            change_list.append(change_place - 1)
            change_place = change_place + diff

        # Setting alerts to go to the next row in template, changing 
        Row = 1
        for form in formset :
            for number in change_list :
                if form.prefix == f'form-{number - (demensions_number - 1)}' :
                    form.keywargs = f'Row-{Row}'
                    Row = Row + 1

            
        # Setting alerts to go the next coulmn in template, defining kwargs for each form in formset
        column = 1
        for form in formset :
            form.form_kwargs = f'Column-{column} : '
            column = column + 1
            if column > demensions_number :
                column = column - demensions_number

    
        context = {'formset' : formset, 'demensions' : demensions_number}
        return render(request, "calculator/matrix_elements.html", context)     

    else :
        return redirect('calculator:main_page')


def result(request) :
    """Calculates the determinan of matrix and shows it in template"""

    if 'form-TOTAL_FORMS' in request.POST.keys() :
        
        demensions = int(request.POST['form-TOTAL_FORMS'])

        # Extracting matrix numbers from request forms and putting them in member list
        members = []
        for i in range(demensions) :
            member =  request.POST[f'form-{i}-matrix_members']
            
            # Change numbers to integer
            if bool(member) == False :
                member = 0

            try:
                member = int(member)
            except ValueError :
                member = int(float(member))
    
            members.append(member)

        # Making a final list based on list(rows) in lists
        change_place = int(demensions / sqrt(demensions) )
        change_list = []
        diff = change_place
        
        # See in wich indexes should program make nest row
        while (change_place <= demensions) :
            change_list.append(change_place - 1)
            change_place = change_place + diff

        # Braking the matrix into ((length)/demensions) parts
        rows = {}
        row = 0
        for j in range(demensions) :
            if f"row-{row+1}" not in rows.keys() :
                rows[f'row-{row+1}'] = []
            rows[f'row-{row+1}'].append(members[j])
            if j in change_list :
                row = row + 1

        # Final list that contains the final format of matrix
        matrix = []
        for value in rows.values() :
            matrix.append(value)       

        # Matrix is 1*1
        if sqrt(demensions) == 1 :
            determinant =  matrix[0][0]

        # Matrix is 2*2
        if sqrt(demensions) == 2 :
            determinant = two_in_two_matrix(matrix, sqrt(demensions))

        # Matrix is bigger than 2*2
        if sqrt(demensions) > 2 :
            determinant = big_matrix(matrix, sqrt(demensions))

        context = {'members' : members, 'matrix' : matrix, 'determinant' : determinant}
        return render(request, 'calculator/result.html', context)

    else :
        return redirect('calculator:main_page')    

calculator/templates/calculator/base.html
{% load bootstrap5 %}

<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,
        initial-scale=1, shrink-to-fit=no">
        <title>ِDeterminant Calculator</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% bootstrap_messages %}
    </head>

    <body>

        <div id="navbar" class="mb-4">
            <nav class="navbar navbar-dark bg-dark">
                <div class="container justify-content-center"  >
                <a class="navbar-brand" href="{% url 'calculator:main_page' %}">
                    <span style="text-align: center;">Determinant Calculator</span>
                </a>
                </div>
            </nav>
        </div>

        <main>
            <div>
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    
        
    </body>

    <nav class="navbar fixed-bottom navbar-dark bg-primary py-0 text-end">
        <div class="container justify-content-center">
          <a class="navbar-brand text-dark" href="http://www.usc.ac.ir/"><span style="text-decoration: underline; color: white;">University of Science and Culture</span> </a>
    </nav>

</html>

calculator/templates/calculator/main_page.html
{% extends "calculator/base.html" %}

{% load bootstrap5 %}


{% block page_header %}{% endblock page_header %}

{% block content%}

<div class="jumbotron">
    <h1 class="display-4">Welcome ! </h1>
    <br></br>
    <p class="text-primary" style="font-size: x-large" >You can calculate the determinant of sqaure Matrices here. </p>
    <hr class="my-4">
    <p>Enter (N) which is the Dimension of your N*N matrix. [N must be between 1 to 9]</p>
    <p class="lead">
        <form class="form" action ="{% url 'calculator:set_demensions' %}" method = "post">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
                <button class="btn btn-info" name="submit">Submit</button>
            {% endbuttons %}
        </form>
    
    </p>
  </div>

{% endblock content%}

calculator/templates/calculator/matrix_elements.html
{% extends "calculator/base.html" %}

{% load bootstrap5 %}


{% block page_header %}
  <p style="text-align: center; font-size: x-large;" class="text-primary">Please enter the data into matrix cells</p>
{% endblock page_header %}

<br></br>

{% block content %}
  <div style="display: block; text-align: center;">
  <form class="form" style="margin: auto;" action ="{% url 'calculator:result' %}" method = "post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}

      {%  if form.keywargs %}
      <div class="mb-3"></div>
        <div style="text-align: center;" class="mb-4">
          <!--Number of row-->
          <span style="text-decoration: underline;" >{{ form.keywargs }}</span> <span style="color: black">&cudarrr;</span>
        </div>

      {% endif %} 


      <span class="text-primary" >{{ form.form_kwargs }}</span>
      {{ form.as_table }}
      <div class="mb-2"></div>

    {% endfor %}

  <br></br>

  <input class="btn btn-info" type="submit" value="Submit">
  </form>

  <br></br>
  <br></br>

  </div>
{% endblock content %}

calculator/templates/calculator/result.html
{% extends "calculator/base.html" %}


{% block page_header %}
  <p class="text-primary" style="font-size: x-large; text-align: center;">The determinant of your matrix = <span style="text-decoration: underline;" class="text-success" >{{ determinant }}</span></p>
{% endblock page_header %}

{% block content %}

  <p style="text-align: center; font-size: x-large;" class="text-primary">Your matrix : </p>
  <div style="text-align: center;"> 
    {% for row in matrix %}
      {% for column in row %}
        <span class="text-success" style="font-size: large;">{{ column }} </span>&nbsp;
      {% endfor %}
      <br></br>
    {% endfor %}
    <br></br>
  </div>
{% endblock content %}    